/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './jumbotron';
const styles_JumbotronComponent:any[] = ([] as any[]);
export const RenderType_JumbotronComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_JumbotronComponent,data:{}});
export function View_JumbotronComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'jumbotron']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Jumbo'])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_JumbotronComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'jumbotron',([] as any[]),
      (null as any),(null as any),(null as any),View_JumbotronComponent_0,RenderType_JumbotronComponent)),
      i0.ɵdid(49152,(null as any),0,i1.JumbotronComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const JumbotronComponentNgFactory:i0.ComponentFactory<i1.JumbotronComponent> = i0.ɵccf('jumbotron',
    i1.JumbotronComponent,View_JumbotronComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2p1bWJvdHJvbi9qdW1ib3Ryb24ubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2p1bWJvdHJvbi9qdW1ib3Ryb24udHMiLCJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2p1bWJvdHJvbi9qdW1ib3Ryb24udHMuSnVtYm90cm9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImp1bWJvdHJvblwiPlxyXG4gICAgPGgxPkp1bWJvPC9oMT5cclxuPC9kaXY+IiwiPGp1bWJvdHJvbj48L2p1bWJvdHJvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUEsZ0JBQUksMENBQVU7VUFBQTs7O29CQ0RsQjtNQUFBO2FBQUE7VUFBQTs7OyJ9
