/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './jumbotron';
const styles_JumbotronComponent:any[] = ([] as any[]);
export const RenderType_JumbotronComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_JumbotronComponent,data:{}});
export function View_JumbotronComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'jumbotron']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Jumbo'])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_JumbotronComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'jumbotron',([] as any[]),
      (null as any),(null as any),(null as any),View_JumbotronComponent_0,RenderType_JumbotronComponent)),
      i0.ɵdid(49152,(null as any),0,i1.JumbotronComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const JumbotronComponentNgFactory:i0.ComponentFactory<i1.JumbotronComponent> = i0.ɵccf('jumbotron',
    i1.JumbotronComponent,View_JumbotronComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXItYm9pbGVycGxhdGUvY2xpZW50L2FwcC9jb250cm9scy9qdW1ib3Ryb24vanVtYm90cm9uLnRzIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi50cy5KdW1ib3Ryb25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XHJcbiAgICA8aDE+SnVtYm88L2gxPlxyXG48L2Rpdj4iLCI8anVtYm90cm9uPjwvanVtYm90cm9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBdUIsMkNBQ25CO1VBQUE7VUFBQSxnQkFBSSwwQ0FBVTtVQUFBOzs7b0JDRGxCO01BQUE7YUFBQTtVQUFBOzs7In0=
