/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../controls/navbar/navbar.ngfactory';
import * as i2 from '../../controls/navbar/navbar';
import * as i3 from '@angular/router';
import * as i4 from '../../controls/footer/footer.ngfactory';
import * as i5 from '../../controls/footer/footer';
import * as i6 from './default';
const styles_DefaultLayout:any[] = ([] as any[]);
export const RenderType_DefaultLayout:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_DefaultLayout,data:{}});
export function View_DefaultLayout_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'wrapper']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'navbar',[['class','sidebar']],(null as any),(null as any),(null as any),
          i1.View_NavbarComponent_0,i1.RenderType_NavbarComponent)),i0.ɵdid(49152,
          (null as any),0,i2.NavbarComponent,([] as any[]),{navs:[0,'navs']},(null as any)),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','content']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'footer',[['class','footer']],(null as any),(null as any),
          (null as any),i4.View_FooterComponent_0,i4.RenderType_FooterComponent)),
      i0.ɵdid(49152,(null as any),0,i5.FooterComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n\n']))],(_ck,_v) => {
    var _co:i6.DefaultLayout = _v.component;
    const currVal_0:any = _co.navs;
    _ck(_v,3,0,currVal_0);
    _ck(_v,8,0);
  },(null as any));
}
export function View_DefaultLayout_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'application',
      ([] as any[]),(null as any),(null as any),(null as any),View_DefaultLayout_0,
      RenderType_DefaultLayout)),i0.ɵdid(49152,(null as any),0,i6.DefaultLayout,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const DefaultLayoutNgFactory:i0.ComponentFactory<i6.DefaultLayout> = i0.ɵccf('application',
    i6.DefaultLayout,View_DefaultLayout_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2xheW91dHMvZGVmYXVsdC9kZWZhdWx0Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9sYXlvdXRzL2RlZmF1bHQvZGVmYXVsdC50cyIsIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9sYXlvdXRzL2RlZmF1bHQvZGVmYXVsdC5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2xheW91dHMvZGVmYXVsdC9kZWZhdWx0LnRzLkRlZmF1bHRMYXlvdXRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwid3JhcHBlclwiPlxyXG4gICAgPG5hdmJhciBjbGFzcz1cInNpZGViYXJcIiBbbmF2c109XCJuYXZzXCI+PC9uYXZiYXI+XHJcbiAgICA8ZGl2IGNsYXNzPVwiY29udGVudFwiPlxyXG4gICAgICAgIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cclxuICAgIDwvZGl2PlxyXG48L2Rpdj5cclxuPGZvb3RlciBjbGFzcz1cImZvb3RlclwiPjwvZm9vdGVyPlxyXG5cclxuIiwiPGFwcGxpY2F0aW9uPjwvYXBwbGljYXRpb24+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXFCLDJDQUNqQjtVQUFBO2lFQUFBLFVBQUE7VUFBQTtNQUErQywyQ0FDL0M7VUFBQTtVQUFBLDhCQUFxQjtNQUNqQjtVQUFBO2FBQUE7c0NBQUE7VUFBQSxlQUErQiwyQ0FDN0I7VUFBQSxTQUNKLHVDQUNOO1VBQUE7VUFBQTthQUFBO1VBQUEsZUFBZ0M7O0lBTEo7SUFBeEIsV0FBd0IsU0FBeEI7SUFFSTs7OztvQkNIUjtNQUFBOzhCQUFBLFVBQUE7TUFBQTs7OyJ9
