/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './control1';
import * as i2 from '../../services/communicate';
const styles_Control1Control:any[] = ([] as any[]);
export const RenderType_Control1Control:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Control1Control,data:{}});
export function View_Control1Control_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'ctrl1']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Контрол 1'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_Control1Control_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'control1',([] as any[]),
      (null as any),(null as any),(null as any),View_Control1Control_0,RenderType_Control1Control)),
      i0.ɵdid(49152,(null as any),0,i1.Control1Control,[i2.CommunicateService],(null as any),
          (null as any))],(null as any),(null as any));
}
export const Control1ControlNgFactory:i0.ComponentFactory<i1.Control1Control> = i0.ɵccf('control1',
    i1.Control1Control,View_Control1Control_Host_0,{logger:'logger'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDEvY29udHJvbDEubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDEvY29udHJvbDEudHMiLCJuZzovLy9DOi9TYW1wbGUvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9jb250cm9scy9jb250cm9sMS9jb250cm9sMS5odG1sIiwibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDEvY29udHJvbDEudHMuQ29udHJvbDFDb250cm9sX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImN0cmwxXCI+XHJcbiAgICA8aDI+0JrQvtC90YLRgNC+0LsgMTwvaDI+XHJcbjwvZGl2PlxyXG4iLCI8Y29udHJvbDE+PC9jb250cm9sMT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFtQiwyQ0FDZjtVQUFBO1VBQUEsZ0JBQUksOENBQWM7VUFBQSxTQUNoQjs7O29CQ0ZOO01BQUE7YUFBQTtVQUFBOzs7In0=
