/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './control4';
const styles_Control4Control:any[] = ([] as any[]);
export const RenderType_Control4Control:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Control4Control,data:{}});
export function View_Control4Control_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'sub4']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    Подкомпонент 4\n']))],(null as any),(null as any));
}
export function View_Control4Control_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'control4',([] as any[]),
      (null as any),(null as any),(null as any),View_Control4Control_0,RenderType_Control4Control)),
      i0.ɵdid(49152,(null as any),0,i1.Control4Control,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const Control4ControlNgFactory:i0.ComponentFactory<i1.Control4Control> = i0.ɵccf('control4',
    i1.Control4Control,View_Control4Control_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDQvY29udHJvbDQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDQvY29udHJvbDQudHMiLCJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXItYm9pbGVycGxhdGUvY2xpZW50L2FwcC9jb250cm9scy9jb250cm9sNC9jb250cm9sNC5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDQvY29udHJvbDQudHMuQ29udHJvbDRDb250cm9sX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInN1YjRcIj5cclxuICAgINCf0L7QtNC60L7QvNC/0L7QvdC10L3RgiA0XHJcbjwvZGl2PiIsIjxjb250cm9sND48L2NvbnRyb2w0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBa0I7OztvQkNBbEI7TUFBQTthQUFBO1VBQUE7OzsifQ==
