/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './control4';
const styles_Control4Control:any[] = ([] as any[]);
export const RenderType_Control4Control:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Control4Control,data:{}});
export function View_Control4Control_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'sub4']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    Подкомпонент 4\n']))],(null as any),(null as any));
}
export function View_Control4Control_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'control4',([] as any[]),
      (null as any),(null as any),(null as any),View_Control4Control_0,RenderType_Control4Control)),
      i0.ɵdid(49152,(null as any),0,i1.Control4Control,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const Control4ControlNgFactory:i0.ComponentFactory<i1.Control4Control> = i0.ɵccf('control4',
    i1.Control4Control,View_Control4Control_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2NvbnRyb2w0L2NvbnRyb2w0Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9jb250cm9scy9jb250cm9sNC9jb250cm9sNC50cyIsIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9jb250cm9scy9jb250cm9sNC9jb250cm9sNC5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2NvbnRyb2w0L2NvbnRyb2w0LnRzLkNvbnRyb2w0Q29udHJvbF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJzdWI0XCI+XHJcbiAgICDQn9C+0LTQutC+0LzQv9C+0L3QtdC90YIgNFxyXG48L2Rpdj4iLCI8Y29udHJvbDQ+PC9jb250cm9sND4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQWtCOzs7b0JDQWxCO01BQUE7YUFBQTtVQUFBOzs7In0=
