/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
const styles_IndexPage:any[] = ([] as any[]);
export const RenderType_IndexPage:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_IndexPage,
    data:{}});
export function View_IndexPage_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'col-xs-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Главная'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_IndexPage_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'index',([] as any[]),
      (null as any),(null as any),(null as any),View_IndexPage_0,RenderType_IndexPage)),
      i0.ɵdid(49152,(null as any),0,i1.IndexPage,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const IndexPageNgFactory:i0.ComponentFactory<i1.IndexPage> = i0.ɵccf('index',
    i1.IndexPage,View_IndexPage_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL3BhZ2VzL2luZGV4L2luZGV4Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9pbmRleC9pbmRleC50cyIsIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9pbmRleC9pbmRleC5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL3BhZ2VzL2luZGV4L2luZGV4LnRzLkluZGV4UGFnZV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb2wteHMtMTJcIj5cclxuICAgIDxoMj7Qk9C70LDQstC90LDRjzwvaDI+XHJcbjwvZGl2PlxyXG4iLCI8aW5kZXg+PC9pbmRleD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUEsZ0JBQUksNENBQVk7VUFBQSxTQUNkOzs7b0JDRk47TUFBQTthQUFBOzs7OyJ9
