/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
import * as i2 from '../../providers/data';
const styles_IndexPage:any[] = ([] as any[]);
export const RenderType_IndexPage:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_IndexPage,
    data:{}});
export function View_IndexPage_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'col-xs-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Главная'])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['',''])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    var _co:i1.IndexPage = _v.component;
    const currVal_0:any = _co.test;
    _ck(_v,6,0,currVal_0);
  });
}
export function View_IndexPage_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'index',([] as any[]),
      (null as any),(null as any),(null as any),View_IndexPage_0,RenderType_IndexPage)),
      i0.ɵdid(114688,(null as any),0,i1.IndexPage,[i2.DataProvider],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const IndexPageNgFactory:i0.ComponentFactory<i1.IndexPage> = i0.ɵccf('index',
    i1.IndexPage,View_IndexPage_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvcGFnZXMvaW5kZXgvaW5kZXgubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvcGFnZXMvaW5kZXgvaW5kZXgudHMiLCJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXItYm9pbGVycGxhdGUvY2xpZW50L2FwcC9wYWdlcy9pbmRleC9pbmRleC5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvcGFnZXMvaW5kZXgvaW5kZXgudHMuSW5kZXhQYWdlX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbC14cy0xMlwiPlxyXG4gICAgPGgyPtCT0LvQsNCy0L3QsNGPPC9oMj5cclxuICAgIDxkaXY+e3t0ZXN0fX08L2Rpdj5cclxuPC9kaXY+XHJcbiIsIjxpbmRleD48L2luZGV4PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUEsZ0JBQUksNENBQVk7VUFBQSxhQUNoQjtVQUFBO01BQUssd0NBQWM7TUFDakI7O0lBREc7SUFBQTs7OztvQkNGVDtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
