/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from './master2';
const styles_Master2Layout:any[] = ([] as any[]);
export const RenderType_Master2Layout:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Master2Layout,data:{}});
export function View_Master2Layout_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',[['class',
      'col-xs-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['шаблон 2'])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,4,0);
  },(null as any));
}
export function View_Master2Layout_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'master2',([] as any[]),
      (null as any),(null as any),(null as any),View_Master2Layout_0,RenderType_Master2Layout)),
      i0.ɵdid(49152,(null as any),0,i2.Master2Layout,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Master2LayoutNgFactory:i0.ComponentFactory<i2.Master2Layout> = i0.ɵccf('master2',
    i2.Master2Layout,View_Master2Layout_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvbGF5b3V0cy9tYXN0ZXIyL21hc3RlcjIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvbGF5b3V0cy9tYXN0ZXIyL21hc3RlcjIudHMiLCJuZzovLy9DOi9TYW1wbGUvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9sYXlvdXRzL21hc3RlcjIvbWFzdGVyMi5odG1sIiwibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvbGF5b3V0cy9tYXN0ZXIyL21hc3RlcjIudHMuTWFzdGVyMkxheW91dF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMSBjbGFzcz1cImNvbC14cy0xMlwiPtGI0LDQsdC70L7QvSAyPC9oMT5cclxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PiIsIjxtYXN0ZXIyPjwvbWFzdGVyMj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFzQiw2Q0FBYTtNQUNuQztVQUFBO2FBQUE7c0NBQUE7VUFBQTtJQUFBOzs7O29CQ0RBO01BQUE7YUFBQTs7OzsifQ==
