/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './footer';
const styles_FooterComponent:any[] = ([] as any[]);
export const RenderType_FooterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_FooterComponent,data:{}});
export function View_FooterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'footer']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    фуутер\n']))],(null as any),(null as any));
}
export function View_FooterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'footer',([] as any[]),
      (null as any),(null as any),(null as any),View_FooterComponent_0,RenderType_FooterComponent)),
      i0.ɵdid(49152,(null as any),0,i1.FooterComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const FooterComponentNgFactory:i0.ComponentFactory<i1.FooterComponent> = i0.ɵccf('footer',
    i1.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvZm9vdGVyL2Zvb3Rlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9TYW1wbGUvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9jb250cm9scy9mb290ZXIvZm9vdGVyLnRzIiwibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvZm9vdGVyL2Zvb3Rlci5odG1sIiwibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvZm9vdGVyL2Zvb3Rlci50cy5Gb290ZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiZm9vdGVyXCI+XHJcbiAgICDRhNGD0YPRgtC10YBcclxuPC9kaXY+IiwiPGZvb3Rlcj48L2Zvb3Rlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQW9COzs7b0JDQXBCO01BQUE7YUFBQTtVQUFBOzs7In0=
