/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './footer';
const styles_FooterComponent:any[] = ([] as any[]);
export const RenderType_FooterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_FooterComponent,data:{}});
export function View_FooterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'footer']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    фуутер\n']))],(null as any),(null as any));
}
export function View_FooterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'footer',([] as any[]),
      (null as any),(null as any),(null as any),View_FooterComponent_0,RenderType_FooterComponent)),
      i0.ɵdid(49152,(null as any),0,i1.FooterComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const FooterComponentNgFactory:i0.ComponentFactory<i1.FooterComponent> = i0.ɵccf('footer',
    i1.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2Zvb3Rlci9mb290ZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2Zvb3Rlci9mb290ZXIudHMiLCJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvY29udHJvbHMvZm9vdGVyL2Zvb3Rlci5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2NvbnRyb2xzL2Zvb3Rlci9mb290ZXIudHMuRm9vdGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImZvb3RlclwiPlxyXG4gICAg0YTRg9GD0YLQtdGAXHJcbjwvZGl2PiIsIjxmb290ZXI+PC9mb290ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFvQjs7O29CQ0FwQjtNQUFBO2FBQUE7VUFBQTs7OyJ9
