/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from './master1';
const styles_Master1Layout:any[] = ([] as any[]);
export const RenderType_Master1Layout:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Master1Layout,data:{}});
export function View_Master1Layout_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',[['class',
      'col-xs-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['шаблон 1'])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,4,0);
  },(null as any));
}
export function View_Master1Layout_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'master1',([] as any[]),
      (null as any),(null as any),(null as any),View_Master1Layout_0,RenderType_Master1Layout)),
      i0.ɵdid(49152,(null as any),0,i2.Master1Layout,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Master1LayoutNgFactory:i0.ComponentFactory<i2.Master1Layout> = i0.ɵccf('master1',
    i2.Master1Layout,View_Master1Layout_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2xheW91dHMvbWFzdGVyMS9tYXN0ZXIxLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9sYXlvdXRzL21hc3RlcjEvbWFzdGVyMS50cyIsIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9sYXlvdXRzL21hc3RlcjEvbWFzdGVyMS5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL2xheW91dHMvbWFzdGVyMS9tYXN0ZXIxLnRzLk1hc3RlcjFMYXlvdXRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDEgY2xhc3M9XCJjb2wteHMtMTJcIj7RiNCw0LHQu9C+0L0gMTwvaDE+XHJcbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD4iLCI8bWFzdGVyMT48L21hc3RlcjE+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBc0IsNkNBQWE7TUFDbkM7VUFBQTthQUFBO3NDQUFBO1VBQUE7SUFBQTs7OztvQkNEQTtNQUFBO2FBQUE7Ozs7In0=
