/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../controls/control1/control1.ngfactory';
import * as i2 from '../../controls/control1/control1';
import * as i3 from '../../services/communicate';
import * as i4 from './page1';
const styles_Page1Page:any[] = ([] as any[]);
export const RenderType_Page1Page:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Page1Page,
    data:{}});
export function View_Page1Page_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{control1:0}),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),16,'div',[['class','container']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),13,'div',[['class','row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'col-xs-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Страница 1'])),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'control1',([] as any[]),(null as any),(null as any),(null as any),
          i1.View_Control1Control_0,i1.RenderType_Control1Control)),i0.ɵdid(49152,
          [[1,4]],0,i2.Control1Control,[i3.CommunicateService],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'button',[['class','btn btn-default']],(null as any),[[(null as any),
              'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i4.Page1Page = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.clickHandler()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Нажать'])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_Page1Page_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page1',([] as any[]),
      (null as any),(null as any),(null as any),View_Page1Page_0,RenderType_Page1Page)),
      i0.ɵdid(49152,(null as any),0,i4.Page1Page,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Page1PageNgFactory:i0.ComponentFactory<i4.Page1Page> = i0.ɵccf('page1',
    i4.Page1Page,View_Page1Page_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvcGFnZXMvcGFnZTEvcGFnZTEubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvcGFnZXMvcGFnZTEvcGFnZTEudHMiLCJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXItYm9pbGVycGxhdGUvY2xpZW50L2FwcC9wYWdlcy9wYWdlMS9wYWdlMS5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvcGFnZXMvcGFnZTEvcGFnZTEudHMuUGFnZTFQYWdlX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxyXG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wteHMtMTJcIj5cclxuICAgICAgICAgICAgPGgyPtCh0YLRgNCw0L3QuNGG0LAgMTwvaDI+XHJcbiAgICAgICAgPGNvbnRyb2wxPjwvY29udHJvbDE+XHJcbiAgICAgICAgPGJ1dHRvbiBjbGFzcz1cImJ0biBidG4tZGVmYXVsdFwiIChjbGljayk9XCJjbGlja0hhbmRsZXIoKVwiPtCd0LDQttCw0YLRjDwvYnV0dG9uPlxyXG4gICAgPC9kaXY+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+IiwiPHBhZ2UxPjwvcGFnZTE+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7c0RDQUE7TUFBQTtNQUFBLDhCQUF1QiwyQ0FDbkI7YUFBQTtVQUFBLDBEQUFpQjtNQUFBLGlCQUNiO01BQUE7TUFBdUIsbURBQ25CO1VBQUE7VUFBQSw4QkFBSTtNQUFlLCtDQUN2QjtVQUFBO2lFQUFBLFVBQUE7VUFBQTtNQUFxQiwrQ0FDckI7VUFBQTtjQUFBO1lBQUE7WUFBQTtZQUFnQztjQUFBO2NBQUE7WUFBQTtZQUFoQztVQUFBLGdDQUF5RDtNQUFlLDJDQUN0RTtNQUNBOzs7b0JDUFY7TUFBQTthQUFBOzs7OyJ9
