/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../controls/control1/control1.ngfactory';
import * as i2 from '../../controls/control1/control1';
import * as i3 from '../../services/communicate';
import * as i4 from './page1';
const styles_Page1Page:any[] = ([] as any[]);
export const RenderType_Page1Page:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Page1Page,
    data:{}});
export function View_Page1Page_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{control1:0}),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),16,'div',[['class','container']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),13,'div',[['class','row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'col-xs-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Страница 1'])),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'control1',([] as any[]),(null as any),(null as any),(null as any),
          i1.View_Control1Control_0,i1.RenderType_Control1Control)),i0.ɵdid(49152,
          [[1,4]],0,i2.Control1Control,[i3.CommunicateService],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'button',[['class','btn btn-default']],(null as any),[[(null as any),
              'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i4.Page1Page = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.clickHandler()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Нажать'])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_Page1Page_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page1',([] as any[]),
      (null as any),(null as any),(null as any),View_Page1Page_0,RenderType_Page1Page)),
      i0.ɵdid(49152,(null as any),0,i4.Page1Page,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Page1PageNgFactory:i0.ComponentFactory<i4.Page1Page> = i0.ɵccf('page1',
    i4.Page1Page,View_Page1Page_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL3BhZ2VzL3BhZ2UxL3BhZ2UxLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9wYWdlMS9wYWdlMS50cyIsIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9wYWdlMS9wYWdlMS5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL3BhZ2VzL3BhZ2UxL3BhZ2UxLnRzLlBhZ2UxUGFnZV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cclxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cclxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLXhzLTEyXCI+XHJcbiAgICAgICAgICAgIDxoMj7QodGC0YDQsNC90LjRhtCwIDE8L2gyPlxyXG4gICAgICAgIDxjb250cm9sMT48L2NvbnRyb2wxPlxyXG4gICAgICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRlZmF1bHRcIiAoY2xpY2spPVwiY2xpY2tIYW5kbGVyKClcIj7QndCw0LbQsNGC0Yw8L2J1dHRvbj5cclxuICAgIDwvZGl2PlxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PiIsIjxwYWdlMT48L3BhZ2UxPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O3NEQ0FBO01BQUE7TUFBQSw4QkFBdUIsMkNBQ25CO2FBQUE7VUFBQSwwREFBaUI7TUFBQSxpQkFDYjtNQUFBO01BQXVCLG1EQUNuQjtVQUFBO1VBQUEsOEJBQUk7TUFBZSwrQ0FDdkI7VUFBQTtpRUFBQSxVQUFBO1VBQUE7TUFBcUIsK0NBQ3JCO1VBQUE7Y0FBQTtZQUFBO1lBQUE7WUFBZ0M7Y0FBQTtjQUFBO1lBQUE7WUFBaEM7VUFBQSxnQ0FBeUQ7TUFBZSwyQ0FDdEU7TUFDQTs7O29CQ1BWO01BQUE7YUFBQTs7OzsifQ==
