/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './page3';
const styles_Page3Page:any[] = ([] as any[]);
export const RenderType_Page3Page:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Page3Page,
    data:{}});
export function View_Page3Page_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'h2',[['class','col-xs-12']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['Страница 3'])),(_l()(),i0.ɵted((null as any),['\n\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_Page3Page_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page3',([] as any[]),
      (null as any),(null as any),(null as any),View_Page3Page_0,RenderType_Page3Page)),
      i0.ɵdid(49152,(null as any),0,i1.Page3Page,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Page3PageNgFactory:i0.ComponentFactory<i1.Page3Page> = i0.ɵccf('page3',
    i1.Page3Page,View_Page3Page_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL3BhZ2VzL3BhZ2UzL3BhZ2UzLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9wYWdlMy9wYWdlMy50cyIsIm5nOi8vL0M6L1NhbXBsZXMvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9wYWdlMy9wYWdlMy5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyMi13ZWJwYWNrMi9jbGllbnQvYXBwL3BhZ2VzL3BhZ2UzL3BhZ2UzLnRzLlBhZ2UzUGFnZV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cclxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cclxuICAgICAgICA8aDIgY2xhc3M9XCJjb2wteHMtMTJcIj7QodGC0YDQsNC90LjRhtCwIDM8L2gyPlxyXG5cclxuICAgIDwvZGl2PlxyXG48L2Rpdj5cclxuIiwiPHBhZ2UzPjwvcGFnZTM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUF1QiwyQ0FDbkI7VUFBQTtVQUFBLGdCQUFpQiwrQ0FDYjtVQUFBO1VBQUEsMERBQXNCO1VBQUEsaUJBQWUsNkNBRW5DO1VBQUEsU0FDSjs7O29CQ0xOO01BQUE7YUFBQTs7OzsifQ==
