/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './page3';
const styles_Page3Page:any[] = ([] as any[]);
export const RenderType_Page3Page:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Page3Page,
    data:{}});
export function View_Page3Page_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'h2',[['class','col-xs-12']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['Страница 3'])),(_l()(),i0.ɵted((null as any),['\n\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_Page3Page_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page3',([] as any[]),
      (null as any),(null as any),(null as any),View_Page3Page_0,RenderType_Page3Page)),
      i0.ɵdid(49152,(null as any),0,i1.Page3Page,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Page3PageNgFactory:i0.ComponentFactory<i1.Page3Page> = i0.ɵccf('page3',
    i1.Page3Page,View_Page3Page_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvcGFnZXMvcGFnZTMvcGFnZTMubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvcGFnZXMvcGFnZTMvcGFnZTMudHMiLCJuZzovLy9DOi9TYW1wbGUvYW5ndWxhcjItd2VicGFjazIvY2xpZW50L2FwcC9wYWdlcy9wYWdlMy9wYWdlMy5odG1sIiwibmc6Ly8vQzovU2FtcGxlL2FuZ3VsYXIyLXdlYnBhY2syL2NsaWVudC9hcHAvcGFnZXMvcGFnZTMvcGFnZTMudHMuUGFnZTNQYWdlX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxyXG4gICAgICAgIDxoMiBjbGFzcz1cImNvbC14cy0xMlwiPtCh0YLRgNCw0L3QuNGG0LAgMzwvaDI+XHJcblxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PlxyXG4iLCI8cGFnZTM+PC9wYWdlMz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUEsZ0JBQWlCLCtDQUNiO1VBQUE7VUFBQSwwREFBc0I7VUFBQSxpQkFBZSw2Q0FFbkM7VUFBQSxTQUNKOzs7b0JDTE47TUFBQTthQUFBOzs7OyJ9
