/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './control3';
const styles_Control3Control:any[] = ([] as any[]);
export const RenderType_Control3Control:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Control3Control,data:{}});
export function View_Control3Control_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'sub3']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    Подкомпонент 3\n']))],(null as any),(null as any));
}
export function View_Control3Control_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'control3',([] as any[]),
      (null as any),(null as any),(null as any),View_Control3Control_0,RenderType_Control3Control)),
      i0.ɵdid(49152,(null as any),0,i1.Control3Control,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const Control3ControlNgFactory:i0.ComponentFactory<i1.Control3Control> = i0.ɵccf('control3',
    i1.Control3Control,View_Control3Control_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDMvY29udHJvbDMubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDMvY29udHJvbDMudHMiLCJuZzovLy9DOi9TYW1wbGVzL2FuZ3VsYXItYm9pbGVycGxhdGUvY2xpZW50L2FwcC9jb250cm9scy9jb250cm9sMy9jb250cm9sMy5odG1sIiwibmc6Ly8vQzovU2FtcGxlcy9hbmd1bGFyLWJvaWxlcnBsYXRlL2NsaWVudC9hcHAvY29udHJvbHMvY29udHJvbDMvY29udHJvbDMudHMuQ29udHJvbDNDb250cm9sX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInN1YjNcIj5cclxuICAgINCf0L7QtNC60L7QvNC/0L7QvdC10L3RgiAzXHJcbjwvZGl2PiIsIjxjb250cm9sMz48L2NvbnRyb2wzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBa0I7OztvQkNBbEI7TUFBQTthQUFBO1VBQUE7OzsifQ==
